### ISSUE TITLE
Change in to document methods

### ISSUE THREAD

**Issue by AshikRoyce** [cpt-John/FreahDesk_UI#1]
https://github.com/cpt-John/FreahDesk_UI/blob/588905029deadaafb9dcfda177494eae790dee80/script.js#L62

**Comment by AshikRoyce** [comment]
Hey John,

Can you try to convert everything into document methods. coz raw html hard to maintain

**Comment by cpt-John** [comment]
all tickets ,contacts ,alerts are dynamically added only forms and containers are in html file
