### ISSUE TITLE
errors could be better understandable for the users

### ISSUE THREAD

**Issue by rvsp** [cpt-John/FreahDesk_UI#4]
https://github.com/cpt-John/FreahDesk_UI/blob/594d5e00b2b08c13154169e4686ead514851058e/script.js#L350

in contact creation  & ticket creation could be added more fields(refer doc)

can you try for adding contacts for a ticket, as the flow in freshdesk

**Comment by cpt-John** [comment]
1--> custom bootstrap alerts added(success,danger,warning) with error message received from api response.
2-->added  more fields in create contact and update contact
3-->email is already required for ticket creation also email and name is already shown in ticket card header
